package com.itqf.entity;

import java.util.Date;

public class Provider {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provider.id
     *
     * @mbggenerated Tue Apr 23 14:52:38 CST 2019
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provider.providername
     *
     * @mbggenerated Tue Apr 23 14:52:38 CST 2019
     */
    private String providername;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provider.contactname
     *
     * @mbggenerated Tue Apr 23 14:52:38 CST 2019
     */
    private String contactname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provider.contactphone
     *
     * @mbggenerated Tue Apr 23 14:52:38 CST 2019
     */
    private String contactphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provider.createDate
     *
     * @mbggenerated Tue Apr 23 14:52:38 CST 2019
     */
    private Date createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provider.createid
     *
     * @mbggenerated Tue Apr 23 14:52:38 CST 2019
     */
    private Integer createid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column provider.updateid
     *
     * @mbggenerated Tue Apr 23 14:52:38 CST 2019
     */
    private Integer updateid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provider.id
     *
     * @return the value of provider.id
     *
     * @mbggenerated Tue Apr 23 14:52:38 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provider.id
     *
     * @param id the value for provider.id
     *
     * @mbggenerated Tue Apr 23 14:52:38 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provider.providername
     *
     * @return the value of provider.providername
     *
     * @mbggenerated Tue Apr 23 14:52:38 CST 2019
     */
    public String getProvidername() {
        return providername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provider.providername
     *
     * @param providername the value for provider.providername
     *
     * @mbggenerated Tue Apr 23 14:52:38 CST 2019
     */
    public void setProvidername(String providername) {
        this.providername = providername == null ? null : providername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provider.contactname
     *
     * @return the value of provider.contactname
     *
     * @mbggenerated Tue Apr 23 14:52:38 CST 2019
     */
    public String getContactname() {
        return contactname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provider.contactname
     *
     * @param contactname the value for provider.contactname
     *
     * @mbggenerated Tue Apr 23 14:52:38 CST 2019
     */
    public void setContactname(String contactname) {
        this.contactname = contactname == null ? null : contactname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provider.contactphone
     *
     * @return the value of provider.contactphone
     *
     * @mbggenerated Tue Apr 23 14:52:38 CST 2019
     */
    public String getContactphone() {
        return contactphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provider.contactphone
     *
     * @param contactphone the value for provider.contactphone
     *
     * @mbggenerated Tue Apr 23 14:52:38 CST 2019
     */
    public void setContactphone(String contactphone) {
        this.contactphone = contactphone == null ? null : contactphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provider.createDate
     *
     * @return the value of provider.createDate
     *
     * @mbggenerated Tue Apr 23 14:52:38 CST 2019
     */
    public Date getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provider.createDate
     *
     * @param createdate the value for provider.createDate
     *
     * @mbggenerated Tue Apr 23 14:52:38 CST 2019
     */
    public void setCreatedate(Date createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provider.createid
     *
     * @return the value of provider.createid
     *
     * @mbggenerated Tue Apr 23 14:52:38 CST 2019
     */
    public Integer getCreateid() {
        return createid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provider.createid
     *
     * @param createid the value for provider.createid
     *
     * @mbggenerated Tue Apr 23 14:52:38 CST 2019
     */
    public void setCreateid(Integer createid) {
        this.createid = createid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column provider.updateid
     *
     * @return the value of provider.updateid
     *
     * @mbggenerated Tue Apr 23 14:52:38 CST 2019
     */
    public Integer getUpdateid() {
        return updateid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column provider.updateid
     *
     * @param updateid the value for provider.updateid
     *
     * @mbggenerated Tue Apr 23 14:52:38 CST 2019
     */
    public void setUpdateid(Integer updateid) {
        this.updateid = updateid;
    }
}